RISC-V: Don't rely on positional structure initialization
ANBZ: #24418

commit 28ea54bade76e2d47cb8cdb96e427cfb90d3eea7 upstream.

Without this I get a bunch of warnings along the lines of

    arch/riscv/kernel/module.c:535:26: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
      535 |         [R_RISCV_32] = { apply_r_riscv_32_rela },

This just mades the member initializers explicit instead of positional.
I also aligned some of the table, but mostly just to make the batch
editing go faster.

Fixes: b51fc88cb35e ("Merge patch series "riscv: Add remaining module relocations and tests"")
Reviewed-by: Charlie Jenkins <charlie@rivosinc.com>
Link: https://lore.kernel.org/r/20231107155529.8368-1-palmer@rivosinc.com
Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>
Signed-off-by: Ruidong Tian <tianruidong@linux.alibaba.com>
Reviewed-by: Fangyu <Yu fangyu.yu@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/5723