KVM: selftests: Fix shift of 32 bit unsigned int more than 32 bits
ANBZ: #34453

commit d21b3c60d6e3917f7388db6bcc455f01c99ee42b upstream.

Currrentl a 32 bit 1u value is being shifted more than 32 bits causing
overflow and incorrect checking of bits 32-63. Fix this by using the
BIT_ULL macro for shifting bits.

Detected by cppcheck:
sev_init2_tests.c:108:34: error: Shifting 32-bit value by 63 bits is
undefined behaviour [shiftTooManyBits]

Fixes: dfc083a181ba ("selftests: kvm: add tests for KVM_SEV_INIT2")
Signed-off-by: Colin Ian King <colin.i.king@gmail.com>
Link: https://lore.kernel.org/r/20240523154102.2236133-1-colin.i.king@gmail.com
Signed-off-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: Gokul K <K.Gokul@amd.com>
Signed-off-by: mohanasv <mohanasv@amd.com>
Reviewed-by: Zongyao Chen <zongyao.chen@linux.alibaba.com>
Reviewed-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/7640