anolis: riscv: Fix compilation error for canary offset exceeding 2047
ANBZ: #35131

    On the RISC-V architecture, enabling KABI causes the canary offset to exceed
the instruction limit of 2047, resulting in compilation errors such as:

cc1: error: '2136' is not a valid offset in '-mstack-protector-guard-offset='

    The fix is as follows: when the canary offset exceeds 2047, enable global mode
to resolve this issue.

Signed-off-by: Gao Rui <gao.rui@zte.com.cn>
Reviewed-by: Fangyu Yu <fangyu.yu@linux.alibaba.com>
Reviewed-by: Ruidong Tian <tianruidong@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/6937