anolis: Completely backport "KVM: arm64: Remove host FPSIMD saving for non-protected KVM"
ANBZ: #31782

In backported anolis commit 73f64c676a6bb ("KVM: arm64: Remove host FPSIMD
saving for non-protected KVM"), it didn't backport completed upstream
commit 8eca7f6d5100, missing the definition of hyp_save_fpsimd_host()
and the field definition in struct kvm_host_data.

Without this patch, anolis CI will report error when building allyes
config:
In file included from arch/arm64/kvm/hyp/nvhe/hyp-main.c:8:
./arch/arm64/kvm/hyp/include/hyp/switch.h:420:13: error: 'kvm_hyp_save_fpsimd_host' used but never defined [-Werror]
  420 | static void kvm_hyp_save_fpsimd_host(struct kvm_vcpu *vcpu);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes it by completely backporting the original upstreamed commit.

Signed-off-by: Jia He <justin.he@arm.com>