media: st-delta: avoid excessive stack usage
ANBZ: #34128

commit 30a4e81edb15329f795df0bd3d3693dd15ee2dd8 stable.

commit 5954ad7d1af92cb6244c5f31216e43af55febbb7 upstream.

Building with a reduced stack warning limit shows that delta_mjpeg_decode()
copies a giant structure to the stack each time but only uses three of
its members:

drivers/media/platform/st/sti/delta/delta-mjpeg-dec.c: In function 'delta_mjpeg_decode':
drivers/media/platform/st/sti/delta/delta-mjpeg-dec.c:427:1: error: the frame size of 1296 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Open-code the passing of the structure members that are actually used here.

Fixes: 433ff5b4a29b ("[media] st-delta: add mjpeg support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Hans Verkuil <hverkuil+cisco@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

Assisted-by: PatchPilot <patchpilot@openanolis.org>
Signed-off-by: Weilin Tong <tongweilin@linux.alibaba.com>