anolis: Revert "perf arm-spe: Support metadata version 2"
ANBZ: #25252

This reverts commit b08d9241591df058c70b46830c7ce0e6ca0e14bf.

Original commit backported upstream commit -
7842a4b6ff698768ccdb13324c3902a069b5d5dd to Anolis with some
mistake. This causes the following build error for perf:

    util/arm-spe.c:1558:1: error: label 'err_free' defined but not used [-Werror=unused-label]
     1558 | err_free:
          | ^~~~~~~~

Signed-off-by: Wei Chen <wei.chen@arm.com>
Reviewed-by: Jay Chen <jkchen@linux.alibaba.com>
Reviewed-by: Shuai Xue <xueshuai@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/6115