anolis: Revert "perf build: Ensure sysreg-defs Makefile respects output dir"
ANBZ: #29971

This reverts commit 8d1050dd6142a69d0a9b44803a71e73014d143c7.

The originally backported patch used the wrong environment variable
when configuring the include path for arm-spe.c. Because anolis will
not write sysreg-defs to the source tree unconditionally as later
upstream. As a result, perf fails to build during a full kAPI build
with the following error:
In file included from util/../../arch/arm64/include/asm/cputype.h:217,
                 from util/arm-spe.c:37:
/home/cloud-kernel/tools/arch/arm64/include/asm/sysreg.h:167:10:
fatal error: asm/sysreg-defs.h: No such file or directory
  167 | #include "asm/sysreg-defs.h"
      |          ^~~~~~~~~~~~~~~~~~~
We will revert that backport and keep arm-spe.c still uses the original
include path.

Signed-off-by: Wei Chen <wei.chen@arm.com>