anolis: sxe: Fix sxe compile errors without CONFIG_PM_SLEEP
ANBZ: #20921

when compile sxe without CONFIG_PM_SLEEP, it is failed:

CC [M]  drivers/net/wireless/ath/ath9k/htc_drv_txrx.o
drivers/net/ethernet/linkdata/sxe/sxepf/sxe_main.c:1071:12: error:
'sxe_resume' defined but not used [-Werror=unused-function]
 1071 | static int sxe_resume(struct device *dev)
      |            ^~~~~~~~~~
drivers/net/ethernet/linkdata/sxe/sxepf/sxe_main.c:1038:12: error:
'sxe_suspend' defined but not used [-Werror=unused-function]
 1038 | static int sxe_suspend(struct device *dev)
      |            ^~~~~~~~~~~

Signed-off-by: liujie_answer <liujie5@linkdatatechnology.com>