tools/testing/cxl: Disable "missing prototypes / declarations" warnings
ANBZ: #26472

commit 68deb9972079c9904fe714c049a7f08bd997a9ee upstream.

Prevent warnings of the form:

tools/testing/cxl/test/mock.c:44:6: error: no previous prototype for
‘__wrap_is_acpi_device_node’ [-Werror=missing-prototypes]

tools/testing/cxl/test/mock.c:63:5: error: no previous prototype for
‘__wrap_acpi_table_parse_cedt’ [-Werror=missing-prototypes]

tools/testing/cxl/test/mock.c:81:13: error: no previous prototype for
‘__wrap_acpi_evaluate_integer’ [-Werror=missing-prototypes]

...by locally disabling some warnings.

It turns out that:

Commit 0fcb70851fbf ("Makefile.extrawarn: turn on missing-prototypes globally")

...in addition to expanding in-tree coverage, also impacts out-of-tree
module builds like those in tools/testing/cxl/.

Filter out the warning options on unit test code that does not effect
mainline builds.

Hygon-SIG: commit 68deb9972079 upstream tools/testing/cxl: Disable "missing
prototypes / declarations" warnings
Backport upstream cxl-6.7 & 6.8 features to anolis branch devel-6.6.

Reviewed-by: Alison Schofield <alison.schofield@intel.com>
Link: https://lore.kernel.org/r/170543983780.460832.10920261849128601697.stgit@dwillia2-xfh.jf.intel.com
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
[ Huaisheng Ye: amend commit log ]
Signed-off-by: Huaisheng Ye <yehuaisheng@hygon.cn>
cc: hygon-arch@list.openanolis.cn