KVM: selftests: Fix printf() format goof in SEV smoke test
ANBZ: #34453

commit 3b2d3db368013729fd2167a0d91fec821dba807c upstream.

Print out the index of mismatching XSAVE bytes using unsigned decimal
format.  Some versions of clang complain about trying to print an integer
as an unsigned char.

  x86/sev_smoke_test.c:55:51: error: format specifies type 'unsigned char'
                                     but the argument has type 'int' [-Werror,-Wformat]

[Backport Changes]

1. In the current backport, changes intended for
tools/testing/selftests/kvm/x86/sev_smoke_test.c were instead applied to
the equivalent file in location
tools/testing/selftests/kvm/x86_64/sev_smoke_test.c, since the upstream
commit 67730e6c53d7 which moved the tools/testing/selftests/kvm/x86_64
related files to tools/testing/selftests/kvm/x86 has not been applied in
the current source tree. Backporting commit 67730e6c53d7 introduces
additional dependencies and unnecessary conflicts. So, the necessary
changes to sev_smoke_test.c were applied at its existing location to
maintain compatibility.

Fixes: 8c53183dbaa2 ("selftests: kvm: add test for transferring FPU state into VMSA")
Link: https://lore.kernel.org/r/20250228233852.3855676-1-seanjc@google.com
Signed-off-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: Rahul Kumar <Kumar.Rahul2@amd.com>
Signed-off-by: mohanasv <mohanasv@amd.com>
Reviewed-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>
Reviewed-by: Zongyao Chen <zongyao.chen@linux.alibaba.com>
Reviewed-by: Bin Guo <guobin@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/7708