anolis: mm: always includes swapops.h in swap.h
ANBZ: #26808

In mm/shmem.c, swap.h is included ahead of swapops.h, thus the function
declared in swap.h which has used swp_offset() will report build issue:
NOTE: if CONFIG_USERFAULTFD is enabled, build issue won't be reported as
shmem_fs.h including chain has already includes swapops.h before swap.h.

[root@localhost cloud-kernel]# make all -j192
  DESCEND objtool
  CALL    scripts/checksyscalls.sh
  INSTALL libsubcmd_headers
  CC      mm/filemap.o
  CC      mm/vmscan.o
  CC      mm/util.o
  CC      mm/shmem.o
  CC      mm/show_mem.o
  CC      mm/memory.o
  CC      mm/mincore.o
  CC      mm/madvise.o
  CC      mm/swap_state.o
  CC      mm/page_io.o
  CC      mm/swapfile.o
  CC      mm/huge_memory.o
In file included from mm/shmem.c:45:
mm/swap.h: In function ‘non_swapcache_batch’:
mm/swap.h:69:19: error: implicit declaration of function ‘swp_offset’; did you mean ‘pud_offset’? [-Werror=implicit-function-declaration]
   69 |  pgoff_t offset = swp_offset(entry);
      |                   ^~~~~~~~~~
      |                   pud_offset
In file included from mm/shmem.c:70:
./include/linux/swapops.h: At top level:
./include/linux/swapops.h:107:23: error: conflicting types for ‘swp_offset’
  107 | static inline pgoff_t swp_offset(swp_entry_t entry)
      |                       ^~~~~~~~~~
In file included from mm/shmem.c:45:
mm/swap.h:69:19: note: previous implicit declaration of ‘swp_offset’ was here
   69 |  pgoff_t offset = swp_offset(entry);
      |                   ^~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: mm/shmem.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:480: mm] Error 2
make[1]: *** [/home/shiyudzl/cloud-kernel/Makefile:1953: .] Error 2
make: *** [Makefile:234: __sub-make] Error 2

Fixes: fbb8a7e89ba3 ("mm/shmem, swap: fix softlockup with mTHP swapin")
Signed-off-by: Zelin Deng <zelin.deng@linux.alibaba.com>
Reviewed-by: Baolin Wang <baolin.wang@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/6162