anolis: iommu: iommupt: Fix odd build issue when GCOV is enabled
ANBZ: #26808

We observed:
       In file included from <command-line>:
       In function 'amdv1pt_install_leaf_entry',
           inlined from '__do_map_single_page' at drivers/iommu/generic_pt/fmt/../iommu_pt.h:651:3,
           inlined from '__map_single_page0' at drivers/iommu/generic_pt/fmt/../iommu_pt.h:662:1,
           inlined from 'pt_descend' at drivers/iommu/generic_pt/fmt/../pt_iter.h:391:9,
           inlined from '__do_map_single_page' at drivers/iommu/generic_pt/fmt/../iommu_pt.h:658:10,
           inlined from '__map_single_page1.constprop' at drivers/iommu/generic_pt/fmt/../iommu_pt.h:662:1:
       ././include/linux/compiler_types.h:631:45: error: call to '__compiletime_assert_251' declared with attribute error: FIELD_PREP: value too large for the field
         631 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
             |                                             ^
       ././include/linux/compiler_types.h:612:25: note: in definition of macro '__compiletime_assert'
         612 |                         prefix ## suffix();                             \
             |                         ^~~~~~
       ././include/linux/compiler_types.h:631:9: note: in expansion of macro '_compiletime_assert'
         631 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
             |         ^~~~~~~~~~~~~~~~~~~
       ./include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
          39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
             |                                     ^~~~~~~~~~~~~~~~~~
       ./include/linux/bitfield.h:69:17: note: in expansion of macro 'BUILD_BUG_ON_MSG'
          69 |                 BUILD_BUG_ON_MSG(__builtin_constant_p(_val) ?           \
             |                 ^~~~~~~~~~~~~~~~
       ./include/linux/bitfield.h:90:17: note: in expansion of macro '__BF_FIELD_CHECK_MASK'
          90 |                 __BF_FIELD_CHECK_MASK(mask, val, pfx);                  \
             |                 ^~~~~~~~~~~~~~~~~~~~~
       ./include/linux/bitfield.h:137:17: note: in expansion of macro '__FIELD_PREP'
         137 |                 __FIELD_PREP(_mask, _val, "FIELD_PREP: ");              \
             |                 ^~~~~~~~~~~~
       drivers/iommu/generic_pt/fmt/amdv1.h:220:26: note: in expansion of macro 'FIELD_PREP'
         220 |                          FIELD_PREP(AMDV1PT_FMT_OA,
             |
It is a really odd compiler issue as compiler cannot get clear this if
condition could never happen.

Fixes: d50caa27202f ("iommupt: Add the AMD IOMMU v1 page table format")
Signed-off-by: Zelin Deng <zelin.deng@linux.alibaba.com>
Reviewed-by: Baolin Wang <baolin.wang@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/7060