anolis: mm: fix unused variable ‘pmd’ warning
ANBZ: #20698

When CONFIG_FS_DAX_PMD is set to 'n', the following warning will appear during compilation.

mm/memory.c: In function ‘fr_apply_vma’:
mm/memory.c:7310:8: error: unused variable ‘pmd’ [-Werror=unused-variable]
  pmd_t pmd;

Signed-off-by: Shao Mingyin <shao.mingyin@zte.com.cn>