tools/testing/nvdimm: Disable "missing prototypes / declarations" warnings
ANBZ: #26472

commit c97dac57c804b53eab492ca0230d86356729d633 upstream.

Prevent warnings of the form:

tools/testing/nvdimm/config_check.c:4:6: error: no previous prototype
for ‘check’ [-Werror=missing-prototypes]

...by locally disabling some warnings.

It turns out that:

Commit 0fcb70851fbf ("Makefile.extrawarn: turn on missing-prototypes globally")

...in addition to expanding in-tree coverage, also impacts out-of-tree
module builds like those in tools/testing/nvdimm/.

Filter out the warning options on unit test code that does not effect
mainline builds.

Hygon-SIG: commit c97dac57c804 upstream tools/testing/nvdimm: Disable "missing
prototypes / declarations" warnings
Backport upstream cxl-6.7 & 6.8 features to anolis branch devel-6.6.

Reviewed-by: Alison Schofield <alison.schofield@intel.com>
Link: https://lore.kernel.org/r/170543984331.460832.1780246477583036191.stgit@dwillia2-xfh.jf.intel.com
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
[ Huaisheng Ye: amend commit log ]
Signed-off-by: Huaisheng Ye <yehuaisheng@hygon.cn>
cc: hygon-arch@list.openanolis.cn