apparmor: use the condition in AA_BUG_FMT even with debug disabled
ANBZ: #31890

commit f8c001884bb4da56ce5617ed6c747ae61a17878f stable.

commit 67e370aa7f968f6a4f3573ed61a77b36d1b26475 upstream.

This follows the established practice and fixes a build failure for me:
security/apparmor/file.c: In function ‘__file_sock_perm’:
security/apparmor/file.c:544:24: error: unused variable ‘sock’ [-Werror=unused-variable]
  544 |         struct socket *sock = (struct socket *) file->private_data;
      |                        ^~~~

Signed-off-by: Mateusz Guzik <mjguzik@gmail.com>
Signed-off-by: John Johansen <john.johansen@canonical.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

Signed-off-by: PatchPilot <patchpilot@openanolis.org>
Signed-off-by: eileen <huangy2023@163.com>