anolis: xfs: fix build failure when CONFIG_FS_DAX is off
ANBZ: #11295

Fix the following build error:

fs/xfs/xfs_reflink.c: In function ‘xfs_reflink_allocate_cow’:
fs/xfs/xfs_reflink.c:518:11: error: too many arguments to function ‘xfs_reflink_unshare_range’
  518 |   error = xfs_reflink_unshare_range(ip, imap,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
fs/xfs/xfs_reflink.c:470:1: note: declared here
  470 | xfs_reflink_unshare_range(

Fixes: 15c8fce763bd ("anolis: xfs: never block page fault during inode inactivation")
Signed-off-by: Joseph Qi <joseph.qi@linux.alibaba.com>