module: Optimize function definition in include/linux/module.h
ANBZ: #38133
commit 32a08c17d8096f0fd2c6600bc5fe8464aaf68ea7 upstream.

When the CONFIG_STRICT_MODULE_RWX is disabled in an architecture, the
following error will occur, which is unreasonable. The architecture's
configuration file and code should be independent of each other.

'''
kernel/module/strict_rwx.c:53:6: error: redefinition of ‘module_enable_ro’
   53 | void module_enable_ro(const struct module *mod, bool after_init)
      |      ^~~~~~~~~~~~~~~~
In file included from kernel/module/strict_rwx.c:8:
./include/linux/module.h:898:20: note: previous definition of ‘module_enable_ro’ with type ‘void(const struct module *, bool)’ {aka ‘void(const struct module *, _Bool)’}
  898 | static inline void module_enable_ro(const struct module *mod, bool after_init) { }
      |                    ^~~~~~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:243: kernel/module/strict_rwx.o] Error 1
'''

The patch applies some modifications submitted upstream, removing inline
function declarations from the 'include/linux/module.h', as the relevant
cases were already handled in the 'kernel/module/strict_rwx.c'.

Signed-off-by: Kanglong Wang <wangkanglong@loongson.cn>
Link: https://gitee.com/anolis/cloud-kernel/pulls/8312
Reviewed-by: Juxin Gao <gaojuxin@loongson.cn>
Reviewed-by: Shuai Xue <xueshuai@linux.alibaba.com>
Reviewed-by: Weilin Tong  <tongweilin@linux.alibaba.com>